-- Fixed Query 1
-- Mistake explanation:
-- The orders table does not contain the city column.
-- City information exists in the customers table, so a JOIN is required.


-- Business meaning:
-- Shows how many orders were made from each customer city.

SELECT 
    customers.city,
    COUNT(*) AS order_count
FROM orders
JOIN customers 
ON orders.customer_id = customers.customer_id
GROUP BY customers.city;

-- Fixed Query 2
-- Mistake explanation:
-- Missing comma between product_name and SUM().
-- Product information must come from products table.

-- Business meaning:
-- Shows revenue generated by each product from completed orders.

SELECT
    products.product_name,
    SUM(orders.quantity * products.price) AS revenue
FROM orders
JOIN products 
ON orders.product_id = products.product_id
WHERE orders.status = 'completed'
GROUP BY products.product_name;

-- Fixed Query 3
-- Mistake explanation:
-- ORDER BY cannot appear after a semicolon.
-- The query ended before sorting.


-- Business meaning:
-- Shows order count grouped by status from highest to lowest.

SELECT 
    status,
    COUNT(*) AS order_count
FROM orders
GROUP BY status
ORDER BY order_count DESC;

-- Fixed Query 4 
-- Mistake explanation:
-- Price does not exist in orders table.
-- Price must be taken from products using JOIN.


-- Business meaning:
-- Shows the total value of each order.

SELECT
    orders.order_id,
    orders.quantity,
    products.price,
    orders.quantity * products.price AS total_amount
FROM orders
JOIN products
ON orders.product_id = products.product_id;

-- Fixed Query 5
-- Mistake explanation:
-- Category does not exist in orders table.
-- Product category must come from products table.

-- Business meaning:
-- Shows quantity sold by product category for completed orders.

SELECT products.category, SUM(quantity) AS total_quantity
FROM orders
JOIN products
ON orders.product_id = products.product_id 
WHERE orders.status = 'completed'
GROUP BY category;


-- Fixed Query 7
-- Mistake explanation:
-- HAVING was placed before GROUP BY.
-- SQL query order requires GROUP BY before HAVING.

-- Business meaning:
-- Finds customers who placed more than one order.


SELECT orders.customer_id, COUNT(*) AS order_count
FROM orders
join customers on customers.customer_id = orders.customer_id
GROUP BY orders.customer_id
HAVING COUNT(*) > 1

-- Fixed Query 8
-- Mistake explanation:
-- JOIN condition is missing.
-- SQL needs to know how tables are connected.

-- Business meaning:
-- Shows each order with the customer's name.

SELECT orders.order_id, customers.customer_name
FROM orders
JOIN customers ON orders.customer_id = customers.customer_id;

-- Fixed Query 9
-- Mistake explanation:
-- This query works but should use product price from products.
-- Added table aliases to make the relationship clearer.

-- Business meaning:
-- Shows which products were ordered and their prices.


SELECT orders.customer_id, products.product_id, products.price
FROM orders
JOIN products ON orders.product_id = products.product_id;


-- Fixed Query 10
-- Mistake explanation:
-- Completed orders generate revenue.
-- The requirement asks for orders that should NOT count as revenue.
-- Pending and cancelled orders should be excluded from revenue.

-- Business meaning:
-- Shows orders that are not successful sales.

SELECT *
FROM orders
WHERE status = 'completed';


